import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import SessionProvider from "../../SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LionHearts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-w-96 ${inter.className}`}>
        <SessionProvider >
            {children}
        </SessionProvider>
      </body>
    </html >
  );
}
