import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/Navbar";
import SessionProvider from "./SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LionHeart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-w-96 ${inter.className}`}>
        <SessionProvider >
          <Navbar />
          <main className="px-4 pt-12 max-w-7xl mx-auto min-w-[300px]">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html >
  );
}
